name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
          uses: actions/checkout@v4

      - name: Docker build, push
          run: |
            docker build -t myfront:latest .
            docker tag my-image:latest 192.168.241.136:5000/my-image:latest
            docker push 192.168.241.136:5000/my-image:latest
