name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker build, tag, and push
        run: |
          docker build -t myfront:latest .
          docker tag myfront:latest http://192.168.241.136:5000/myfront:latest
          docker push http://192.168.241.136:5000/myfront:latest
